# Generated by Django 3.0.2 on 2020-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('class_name', models.CharField(max_length=200, verbose_name='Class_name')),
                ('url', models.CharField(max_length=100, verbose_name='Url')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Header Category',
                'verbose_name_plural': 'Header Categories',
            },
        ),
    ]
