# Generated by Django 3.0.2 on 2020-02-12 14:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_purpose', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Saytın məqsədi')),
                ('technical_glance', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texniki baxış')),
                ('glass_tinting', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Şüşələrinin tündləşdirilməsi')),
                ('fees_and_taxes', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Rüsumlar və vergilər')),
                ('fines', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cərimələr')),
                ('contact_us', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Əlaqə')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text modeli',
                'verbose_name_plural': 'Text modelleri',
            },
        ),
    ]
