# Generated by Django 3.0.2 on 2020-02-12 15:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200212_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='contact_us',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Əlaqə'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='fees_and_taxes',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Rüsumlar və vergilər'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='fines',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Cərimələr'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='glass_tinting',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Şüşələrinin tündləşdirilməsi'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='site_purpose',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Saytın məqsədi'),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='technical_glance',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texniki baxış'),
        ),
    ]
