# Generated by Django 3.0.2 on 2020-03-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200212_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Category name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Category',
                'verbose_name_plural': 'Test Categorys',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('options1', models.CharField(max_length=100, verbose_name='Options 1')),
                ('options2', models.CharField(max_length=100, verbose_name='Options 2')),
                ('options3', models.CharField(max_length=100, verbose_name='Options 3')),
                ('options4', models.CharField(max_length=100, verbose_name='Options 4')),
                ('answer', models.CharField(max_length=100, verbose_name='Answer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TestCategory')),
            ],
            options={
                'verbose_name': 'Question and Answer',
                'verbose_name_plural': 'Question and Answers',
            },
        ),
    ]
